
package UI;

import BLL.CargoBLL; // IMPORTAÇÃO DA CLASSE BLL NECESSÁRIA
import BLL.CodigoDeCadastroBLL;
import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class frmCadCodCadastro extends javax.swing.JFrame {

    private CargoBLL cBLL = new CargoBLL();// INSTÂNCIA DA CLASSE DE CARGO
    private List<CargoBLL> listaDeCargos;
    private CodigoDeCadastroBLL ccBLL = new CodigoDeCadastroBLL();
    private List<CodigoDeCadastroBLL> listaDeCodigos = new LinkedList<>();
    DefaultTableModel tableModel; // MODEL DA TABELA
    
    /**
     * Creates new form frmCadCodCadastro
     */
    public frmCadCodCadastro() {
        initComponents();
        tableModel = (DefaultTableModel) tblCodigosGerados.getModel(); // ASSOCIAR MODEL DA TABELA 
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCargos = new javax.swing.JComboBox<>();
        btnCadCargo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtQtdCodigos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCodigosGerados = new javax.swing.JTable();
        btnCadCodigos = new javax.swing.JButton();
        btnGerarCodigos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("GERAR CÓDIGO PARA O CARGO: ");

        cmbCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCadCargo.setText("OUTRO");
        btnCadCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCargoActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTOS CÓDIGOS:");

        tblCodigosGerados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cargo"
            }
        ));
        jScrollPane1.setViewportView(tblCodigosGerados);

        btnCadCodigos.setText("CADASTRAR CÓDIGOS GERADOS");

        btnGerarCodigos.setText("GERAR");
        btnGerarCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarCodigosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbCargos, 0, 225, Short.MAX_VALUE)
                                .addComponent(txtQtdCodigos))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCadCargo)
                                .addComponent(btnGerarCodigos)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadCargo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQtdCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerarCodigos))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadCodigos, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizarCargos(){
        listaDeCargos = cBLL.Consultar();
        
        cmbCargos.removeAllItems();
        
        for (int i = 0; i < listaDeCargos.size(); i++) {
            cmbCargos.addItem(listaDeCargos.get(i).getCargo());
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        AtualizarCargos();// ATUALIZAR A LISTA DE CARGOS ASSIM QUE O FORMULÁRIO ABRIR
    }//GEN-LAST:event_formWindowOpened

    private void btnCadCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCargoActionPerformed
        // TODO add your handling code here:
        
        frmCadCargo cadCargo = new frmCadCargo();
        cadCargo.setDefaultCloseOperation(HIDE_ON_CLOSE);
        cadCargo.setVisible(true);
    }//GEN-LAST:event_btnCadCargoActionPerformed

    private void btnGerarCodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarCodigosActionPerformed
        // TODO add your handling code here:
        int qtdCodigos = Integer.valueOf(txtQtdCodigos.getText());
        
        int qtdCodigosJaGeradosParaCargo = 0;
        
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            
            if(tableModel.getValueAt(i + 1, 2) == cmbCargos.getSelectedItem().toString()){
                qtdCodigosJaGeradosParaCargo++;
            }
            
        }
        
        for(int i = 0; i < qtdCodigos; i++){
            int codigoDoCargo = listaDeCargos.get(cmbCargos.getSelectedIndex()).getCodigo();
            tableModel.insertRow(tableModel.getRowCount(), new Object[] { ccBLL.GerarProximo(codigoDoCargo), cmbCargos.getSelectedItem().toString()});
        }
        
        ccBLL.ResetarCodigos();
        
    }//GEN-LAST:event_btnGerarCodigosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadCodCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadCodCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadCodCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadCodCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadCodCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadCargo;
    private javax.swing.JButton btnCadCodigos;
    private javax.swing.JButton btnGerarCodigos;
    private javax.swing.JComboBox<String> cmbCargos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCodigosGerados;
    private javax.swing.JTextField txtQtdCodigos;
    // End of variables declaration//GEN-END:variables
}
