/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Guto
 */
public class frmTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmTelaPrincipal
     */
    public frmTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCadJogo = new javax.swing.JMenuItem();
        btnCadEquipamento = new javax.swing.JMenuItem();
        btnFuncionario = new javax.swing.JMenuItem();
        btnCadCodCadastro = new javax.swing.JMenuItem();
        btnCadCargo = new javax.swing.JMenuItem();
        btnCadAluguel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenu1.setText("CADASTRAR");

        btnCadJogo.setText("JOGO");
        btnCadJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadJogoActionPerformed(evt);
            }
        });
        jMenu1.add(btnCadJogo);

        btnCadEquipamento.setText("EQUIPAMENTO");
        btnCadEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEquipamentoActionPerformed(evt);
            }
        });
        jMenu1.add(btnCadEquipamento);

        btnFuncionario.setText("FUNCIONÁRIO");
        jMenu1.add(btnFuncionario);

        btnCadCodCadastro.setText("CÓDIGO DE CADASTRO");
        btnCadCodCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCodCadastroActionPerformed(evt);
            }
        });
        jMenu1.add(btnCadCodCadastro);

        btnCadCargo.setText("CARGO");
        btnCadCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCargoActionPerformed(evt);
            }
        });
        jMenu1.add(btnCadCargo);

        btnCadAluguel.setText("ALUGUEL DE EQUIPAMENTO");
        jMenu1.add(btnCadAluguel);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("CONSULTAR");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadJogoActionPerformed
        // TODO add your handling code here:
        frmCadJogo cadJogo = new frmCadJogo();
        cadJogo.setDefaultCloseOperation(HIDE_ON_CLOSE);
        cadJogo.setVisible(true);
    }//GEN-LAST:event_btnCadJogoActionPerformed

    private void btnCadEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEquipamentoActionPerformed
        // TODO add your handling code here:
        
        // INSTANCIANDO E EXIBINDO FORMULÁRIO PARA CADASTRO DE EQUIPAMENTO
        frmCadEquipamento cadEquipamento = new frmCadEquipamento();
        cadEquipamento.setDefaultCloseOperation(HIDE_ON_CLOSE);
        cadEquipamento.setVisible(true);
    }//GEN-LAST:event_btnCadEquipamentoActionPerformed

    private void btnCadCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCargoActionPerformed
        // TODO add your handling code here:
        
        frmCadCargo cadCargpo = new frmCadCargo();
        cadCargpo.setDefaultCloseOperation(HIDE_ON_CLOSE);
        cadCargpo.setVisible(true);
    }//GEN-LAST:event_btnCadCargoActionPerformed

    private void btnCadCodCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCodCadastroActionPerformed
        // TODO add your handling code here:
        frmCadCodCadastro nome= new  frmCadCodCadastro();
        nome.setVisible(true);
    }//GEN-LAST:event_btnCadCodCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadAluguel;
    private javax.swing.JMenuItem btnCadCargo;
    private javax.swing.JMenuItem btnCadCodCadastro;
    private javax.swing.JMenuItem btnCadEquipamento;
    private javax.swing.JMenuItem btnCadJogo;
    private javax.swing.JMenuItem btnFuncionario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
